# Generated by Django 4.1.6 on 2023-04-12 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_transaction_accounts_account_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
